### ISSUE TITLE
Benchmarking Storage Efficiency of Dojo in terms of Gas Usage

### ISSUE THREAD

**Issue by neotheprogramist** [visoftsolutions/dojo#13]
## Overview

With a goal to achieve optimal storage efficiency, it's essential to evaluate how `Dojo` performs in terms of improving storage efficiency, especially focusing on gas consumption. Between Scarb and Katana, the latter is the preferred choice for benchmarking due to its ability to export gas usage information, unlike Scarb.

## Goals

Conduct a comprehensive benchmark using Katana to measure gas consumption related to storage operations in various scenarios:

1. **Native Storage**: Benchmarking storage operations without integrating Dojo.
2. **Simple Dojo Storage**: Standard storage operations with the integration of Dojo.
3. **Dojo Packing Storage**: Storage operations with Dojo's packing feature.
4. **Dojo Indexing Storage**: Storage operations using Dojo's indexing.

## Proposed Architecture

* Katana running locally (or remotely)
* Dojo contracts as test ground, because of compability with tooling and familiarity for developers
* `proptest` crate generating cases for property testing, failure persistence and regression (as well as async capabilities)
* Each contract is deployed, and called with data generated by proptest
* Fee is read from receipts

## Levels of Test Complexity

To provide a comprehensive understanding of how `Dojo` performs across different use-cases, benchmarking should be carried out under three distinct complexities:

1. **Simple Data Structures**: Mainly basic data structures.
2. **Medium Complexity Data Structures**: Intermediate level structures that offer more complexity than the basic ones but aren't highly intricate.
3. **Complex Data Structures**: Highly intricate structures that are robust and multifaceted.

## Suggested Development Order

1. Basic Katana Setup
   - **Branch Name**: `13-1-basic-katana-setup`
   
2. Simple Test Native Storage
   - **Branch Name**: `13-2-simple-test-native-storage`
   
3. Simple Test Dojo Storage
   - **Branch Name**: `13-3-simple-test-dojo-storage`
   
4. Simple Test Dojo Packing Storage
   - **Branch Name**: `13-4-simple-test-dojo-packing-storage`
   
5. Simple Test Dojo Indexing Storage
   - **Branch Name**: `13-5-simple-test-dojo-indexing-storage`
   
6. Simple Benchmark Native Storage
   - **Branch Name**: `13-6-simple-benchmark-native-storage`
   
7. Simple Benchmark Dojo Storage
   - **Branch Name**: `13-7-simple-benchmark-dojo-storage`
   
8. Simple Benchmark Dojo Packing Storage
   - **Branch Name**: `13-8-simple-benchmark-dojo-packing-storage`
   
9. Simple Benchmark Dojo Indexing Storage
   - **Branch Name**: `13-9-simple-benchmark-dojo-indexing-storage`
   
10. Medium Benchmark Native Storage
    - **Branch Name**: `13-10-medium-benchmark-native-storage`
    
11. Medium Benchmark Dojo Storage
    - **Branch Name**: `13-11-medium-benchmark-dojo-storage`
    
12. Medium Benchmark Dojo Packing Storage
    - **Branch Name**: `13-12-medium-benchmark-dojo-packing-storage`
    
13. Medium Benchmark Dojo Indexing Storage
    - **Branch Name**: `13-13-medium-benchmark-dojo-indexing-storage`
    
14. Complex Benchmark Native Storage
    - **Branch Name**: `13-14-complex-benchmark-native-storage`
    
15. Complex Benchmark Dojo Storage
    - **Branch Name**: `13-15-complex-benchmark-dojo-storage`
    
16. Complex Benchmark Dojo Packing Storage
    - **Branch Name**: `13-16-complex-benchmark-dojo-packing-storage`
    
17. Complex Benchmark Dojo Indexing Storage
    - **Branch Name**: `13-17-complex-benchmark-dojo-indexing-storage`

**Comment by tarrencev** [comment]
In addition, Dojo storage without packing
