### ISSUE TITLE
Execution of Katana Benchmarking

### ISSUE THREAD

**Issue by neotheprogramist** [visoftsolutions/dojo#15]
**Related Main Issue:** [Benchmarking Dojo's Storage Efficiency in Terms of Gas Usage](https://github.com/visoftsolutions/dojo/issues/13)

### Objective

The purpose of this sub-issue is to establish a comprehensive guide for benchmarking using **Katana**, the high-speed local Starknet node tailored for local development alongside `Dojo`. 

### Background

**Katana**, as described in the [official documentation](https://book.dojoengine.org/toolchain/katana/overview.html), is built to bolster local development with Dojo. Its speed and integration capability make it a prime tool for assessing the efficiency of storage operations, especially in a localized development environment.

### Tasks

1. **Exploration of Katana's Benchmarking Features**: 
    - Investigate and document the functionalities and parameters of Katana conducive for benchmarking.
    - Develop a step-by-step guide showcasing how to effectively run benchmarks using Katana.

2. **Collecting and Storing Benchmark Results**:
    - Devise a methodology to extract benchmark results from Katana.
    - Introduce a structured format for capturing and storing these results for analysis.

3. **Interpretation and Reporting**:
    - Identify primary metrics to assess from the benchmark results.
    - Propose a coherent and comprehensive reporting template to showcase the findings.

### Expected Outcome

By the conclusion of this sub-issue, we envision having an established protocol for performing benchmarks using **Katana**. This will not only help in understanding storage efficiency but also contribute to the broader goal set in the main issue.

**Comment by matzayonc** [comment]
Initial research
- Tests can be easily deployed into locally or remotely running `Katana` instance
- Then the `starknet_estimateFee` method from the [API](https://playground.open-rpc.org/?uiSchema%5BappBar%5D%5Bui:splitView%5D=false&schemaUrl=https://raw.githubusercontent.com/starkware-libs/starknet-specs/master/api/starknet_api_openrpc.json&uiSchema%5BappBar%5D%5Bui:input%5D=false&uiSchema%5BappBar%5D%5Bui:darkMode%5D=true&uiSchema%5BappBar%5D%5Bui:examplesDropdown%5D=false) can be used to fetch it in straightforward manner.

**Comment by matzayonc** [comment]
Differences from initial research:
- `estimateFee` is rarely used, needs singature and would need some implementation
- `execute` is simple to do with `cli` or `sozo` as a dependency
- `starknet_getTransactionReceipt` run after `execute` is trivial to implement and containts information about gas
```
{
    "jsonrpc": "2.0",
    "method": "starknet_getTransactionReceipt",
    "params": ["0x61c0f0bb7b4d514d44dea673824acf270c00f750c5525a50403a0d94d6f3afa"],
    "id": 1
}
```
