### ISSUE TITLE
Reactivate API & Implement Onchain Entity Indexing

### ISSUE THREAD

**Issue by neotheprogramist** [visoftsolutions/dojo#3]
## Description:

There's a need to reactivate a currently disabled API. Reference to the API is available here: [world.cairo](https://github.com/dojoengine/dojo/blob/main/crates/dojo-core/src/world.cairo#L473).

## Tasks:

1. **Reactivate the API**: 
   - Bring the currently inactive API back into operation.

2. **Implement Onchain Entity Indexing**: 
   - Enhance the system to support indexing of entities directly on the blockchain.
   - Enable more direct and efficient data queries.

3. **Enable Queries by Component Member Values**: 
   - Index entities to support queries based on their component member values.
   - Allow for more targeted and specific data retrieval.

## Expected Outcome:

Post implementation, the system should have:
- A fully functional and reactivated API.
- Onchain entity indexing capabilities.
- The ability to conduct queries based on component member values.

**Comment by tarrencev** [comment]
This looks good. The initial implementation can support indexing based on exact component value matches.

For example, if we have a struct:

```
struct Game {
    #[indexed]
    round: u8,
}
````

We want to be able to query all games with a particular value for a key. The `entities` api will need to be updated, perhaps something like:

```
/// Returns entity IDs and entities that contain the component state.
        ///
        /// # Arguments
        ///
        /// * `component` - The name of the component to be retrieved.
        /// * `key` - The component member key.
        /// * `value` - The component member valuie.
        ///
        /// # Returns
        ///
        /// * `Span<felt252>` - The entity IDs.
        /// * `Span<Span<felt252>>` - The entities.
        fn entities(
            self: @ContractState, component: felt252, key: felt252, value: felt252 length: usize
        ) -> (Span<felt252>, Span<Span<felt252>>) {
...
}
```

Maintaining the index should be as efficient as possible. We should store a mapping of component values to entities that have that value.

In the case above:

Something like:
```
index_len[component][key][value] = num entities with value for key
index[component][key][value][ index of entity 0 ... index_len ] = entitiy_id
```
